class Department {
  int? id; // id is nullable because it will be generated by SQLite
  String name;

  Department({this.id, required this.name});

  // Convert a Department object into a Map. The keys must correspond to the column names of the database.
  Map<String, dynamic> toMap() {
    var map = <String, dynamic>{
      'name': name,
    };

    if (id != null) {
      map['id'] = id;
    }
    return map;
  }

  // Extract a Department object from a Map
  factory Department.fromMap(Map<String, dynamic> map) {
    return Department(
      id: map['id'],
      name: map['name'],
    );
  }
}
